baseURL = "https://wokron.github.io/"
languageCode = "en-us"
title = "Wokron 的博客"

theme = "PaperMod"

copyright = "©2022-2024 Yitang Yang. All rights reserved."

defaultContentLanguage = "zh"

enableGitInfo = true

enableRobotsTXT = true

buildDrafts = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
ShowShareButtons = true

[params.assets]
favicon = "/img/favicon/96x96.png"
favicon16x16 = "/img/favicon/16x16.png"
favicon32x32 = "/img/favicon/32x32.png"

[params.profileMode]
enabled = true
title = "Wokron 的博客"
subtitle = "This is subtitle"
imageUrl = "/img/profile.jpeg"
imageWidth = 120
imageHeight = 120
imageTitle = "This is me"

[[params.profileMode.buttons]]
name = "我的帖子"
url = "/posts/"

[[params.profileMode.buttons]]
name = "系列文章"
url = "/series/"

[[params.socialIcons]]
name = "email"
url = "mailto:stringcatwok@gmail.com"

[[params.socialIcons]]
name = "qq"
url = "3160114036"

[[params.socialIcons]]
name = "github"
url = "https://github.com/wokron"

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 5

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 15

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 20

[outputs]
home = ['HTML', 'RSS', 'JSON']
