baseURL = "https://wokron.github.io/"
title = "Wokron's Blog"

theme = "PaperMod"

paginate = 6

copyright = "©2022-2024 Yitang Yang. All rights reserved."

defaultContentLanguage = "zh"

enableRobotsTXT = true

buildDrafts = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
env = "production"
description = "Wokron 的个人博客。记录学习、分享经验"
author = "Wokron"
keywords = ["blog", "code", "tutorial"]

ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
showtoc = true

math = true

[params.assets]
favicon = "/img/favicon/96x96.png"
favicon16x16 = "/img/favicon/16x16.png"
favicon32x32 = "/img/favicon/32x32.png"

[params.editPost]
URL = "https://github.com/wokron/wokron.github.io/blob/master/content"
Text = "阅读原文"
appendFilePath = true

[params.profileMode]
enabled = true
title = "Wokron 的博客"
subtitle = "学生党踩坑记录"
imageUrl = "/img/profile.jpeg"
imageTitle = "This is me"

[[params.profileMode.buttons]]
name = "我的帖子"
url = "/posts/"

[[params.profileMode.buttons]]
name = "系列文章"
url = "/series/"

[[params.socialIcons]]
name = "github"
title = "My Github Account"
url = "https://github.com/wokron"

[[params.socialIcons]]
name = "email"
title = "Send Me Email"
url = "mailto:stringcatwok@gmail.com"

[[params.socialIcons]]
name = "qq"
title = "My QQ Account"
url = "mailto:3160114036@qq.com"

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 5

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 15

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "github"
name = "Github Repo"
url = "https://github.com/wokron/wokron.github.io"
weight = 25

[outputs]
home = ['HTML', 'RSS', 'JSON']

[markup.highlight]
noClasses = false

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
